title: Solo RPG Reports
author: 
  name: Dougal Stanton
  email: solorpg@dougalstanton.net

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

baseurl: /rpg

collections:
  reports:
    output: true
    permalink: /:path
