title: Solo RPG Reports
subtitle: Little adventures with rules and dice
masthead_title: Solo RPG
description: Reports of pen-and-paper RPGs played solo
author: 
  name: Dougal Stanton
  email: solorpg@dougalstanton.net
date_format: "%-d %B %Y"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

baseurl: /rpg

collections:
  reports:
    output: true
    permalink: /:path

defaults:
  # _reports
  - scope:
      path: ""
      type: reports
    values:
      read_time: true
      show_date: true
  - scope:
      path: ""
      type: site
    values:
      header.overlay_image: "/assets/images/fox-hyde-Jsh4l4KpCw4-unsplash.jpg"
      header.overlay_color: "#000"
      header.overlay_filter: "0.2"
      header.caption: "Photo: [Fox & Hyde](https://unsplash.com/photos/Jsh4l4KpCw4)"

feed:
  collections:
    reports:
      path: "/solorpg.xml"
atom_feed:
  path: "/rpg/solorpg.xml"
