title: Solo RPG Reports
subtitle: Little adventures with rules and dice
masthead_title: Solo RPG
description: Reports of pen-and-paper RPGs played solo
author: 
  name: Dougal Stanton
  email: solorpg@dougalstanton.net

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

baseurl: /rpg

collections:
  reports:
    output: true
    permalink: /:path

defaults:
  # _reports
  - scope:
      path: ""
      type: reports
    values:
      read_time: true

feed:
  collections:
    reports:
      path: "/rpg/solorpg.xml"
atom_feed:
  path: "/rpg/solorpg.xml"
