title: Solo RPG Reports
author: 
  name: Dougal Stanton
  email: solorpg@dougalstanton.net

remote_theme: seanh/jekyll-theme-oatcake@0.1.25
plugins:
 - jekyll-feed

baseurl: /rpg

collections:
  reports:
    output: true
    permalink: /:path
